<cfprocessingdirective pageEncoding="windows-1252">
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=102&a_id=1&a_name=123&u_id=LL&tm_1=elodie.humbert@etam.fr&tm_2=&a_ad1=57/59 rue Henri Barbusse&a_ad2=92110&a_ad3=CLICHY&f_ad1=123&f_ad2=57/59 rue Henri Barbusse&f_ad3=Centre de coût S038004101&f_ad4=92110&f_ad5=CLICHY">123</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=2&a_id=2&a_name=5 MARS EVENTS&u_id=LL&tm_1=&tm_2=&a_ad1=111 avenue Victoir Hugo&a_ad2=75016&a_ad3=PARIS&f_ad1=5 MARS EVENTS&f_ad2=111, Avenue Victor Hugo&f_ad3=&f_ad4=75016&f_ad5=PARIS">5 MARS EVENTS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=3&a_id=3&a_name=ACADEMIE BASQUE DU SPORT&u_id=LL&tm_1=sylvaindufourcq@academiebasquedusport.fr&tm_2=&a_ad1=Parc des Sports Aguiléra Rue Cino Del Duca&a_ad2=64200&a_ad3=BIARRITZ&f_ad1=ACADEMIE BASQUE DU SPORT&f_ad2=Rue Cino del Duca&f_ad3=&f_ad4=64200&f_ad5=BIARRITZ">ACADEMIE BASQUE DU SPORT</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=4&a_id=4&a_name=ACCO BRANDS FRANCE&u_id=LL&tm_1=sabrina.sylva@acco.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=ACCO BRANDS FRANCE&f_ad2=Imm. l'odyssee batiment c / 2 a 12&f_ad3=2 rue du chemin des femmes&f_ad4=91300&f_ad5=MASSY">ACCO BRANDS FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=5&a_id=5&a_name=ACTEMIUM&u_id=LL&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">ACTEMIUM</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=6&a_id=6&a_name=ADER&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">ADER</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=7&a_id=7&a_name=ADVINI&u_id=LL&tm_1=brigitte.yoris@advini.com&tm_2=&a_ad1=L'enclos&a_ad2=34725&a_ad3=SAINT FÉLIX DE LODEZ&f_ad1=ADVINI&f_ad2= L'ENCLOS&f_ad3=&f_ad4=34725&f_ad5=SAINT FELIX DE LODEZ">ADVINI</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=8&a_id=8&a_name=AFPG&u_id=QB&tm_1=jean-jacques.graff@es.fr&tm_2=&a_ad1=77 rue Claude Bernard&a_ad2=75005&a_ad3=PARIS&f_ad1=AFPG&f_ad2=77 rue Claude Bernard&f_ad3=&f_ad4=75005&f_ad5=PARIS">AFPG</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=12&a_id=9&a_name=AGCS SE&u_id=QB&tm_1=william.prein@allianz.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=ALLIANZ GLOBAL CORPORATE AND SPECIALTY AGCS SE&f_ad2=La defense 9 -tour opus 12 &f_ad3=77 esplanade du General de Gaulle&f_ad4=92800&f_ad5=PUTEAUX">AGCS SE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=9&a_id=10&a_name=AGRAM&u_id=LL&tm_1=l.vabois@agram.fr&tm_2=&a_ad1=ZI Chartres Gellainville, 17, avenue Gustave Eiffel&a_ad2=28080&a_ad3=CHARTRES&f_ad1=AGRAM SAS&f_ad2=Parc industriel Chartres Gellainville&f_ad3=17 Avenue Gustave Eiffel&f_ad4=28080&f_ad5=CHARTRES CEDEX">AGRAM</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=60&a_id=11&a_name=AIRSEA INTERNATIONAL&u_id=LL&tm_1=ketura.telon@crystalgroup.fr&tm_2=&a_ad1=AIR SEA INTERNATIONAL, 4 RUE DU MEUNIER&a_ad2=95700&a_ad3=ROISSY EN FRANCE&f_ad1=AIRSEA INTERNATIONAL&f_ad2=&f_ad3=&f_ad4=&f_ad5=">AIRSEA INTERNATIONAL</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=10&a_id=12&a_name=ALBAN MULLER INTERNATIONAL&u_id=LL&tm_1=martine.lemosse@albanmuller.com&tm_2=&a_ad1=9, ZA Jean Monnet&a_ad2=28630&a_ad3=FONTENAY SUR EURE&f_ad1=ALBAN MULLER INTERNATIONAL&f_ad2=9, ZA Jean Monnet&f_ad3=&f_ad4=28630&f_ad5=FONTENAY SUR EURE">ALBAN MULLER INTERNATIONAL</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=11&a_id=13&a_name=ALL SET FOR&u_id=LL&tm_1=achaulot@allsetfor.com&tm_2=&a_ad1=17 rue Médéric&a_ad2=75017&a_ad3=PARIS&f_ad1=ALL SET FOR&f_ad2=14 rue Thorel&f_ad3=&f_ad4=75002&f_ad5=PARIS">ALL SET FOR</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=100&a_id=14&a_name=ALLIADIS&u_id=LL&tm_1=marieisabelle.moinet@smart-rx.com&tm_2=&a_ad1=3 Impasse des chênes - CS 88633&a_ad2=79026&a_ad3=NIORT CEDEX 9&f_ad1=ALLIADIS&f_ad2=3 Impasse des chênes - CS 88633&f_ad3=&f_ad4=79026&f_ad5=NIORT CEDEX 9">ALLIADIS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=13&a_id=15&a_name=ALLIBERT-TREKKING&u_id=LL&tm_1=h.jaccaz@allibert-trekking.com&tm_2=&a_ad1=Rue de Longifan&a_ad2=38530&a_ad3=CHAPAREILLAN&f_ad1=ALLIBERT-TREKKING&f_ad2=Rue de Longifan&f_ad3=&f_ad4=38530&f_ad5=CHAPAREILLAN">ALLIBERT-TREKKING</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=236&a_id=16&a_name=ALTO SIGNALETIQUE&u_id=VG&tm_1=&tm_2=&a_ad1=38 Boulevard Flandrin&a_ad2=75116&a_ad3=PARIS&f_ad1=YLOS 7&f_ad2=9 Rue Napoléon Ancelin&f_ad3=&f_ad4=78400&f_ad5=CHATOU">ALTO SIGNALETIQUE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=14&a_id=17&a_name=ANDKUS CONSEIL&u_id=LL&tm_1=rodolphe.lefebvre@andkus.fr&tm_2=&a_ad1=138 RUE DE PARIS&a_ad2=94220&a_ad3=CHARENTON LE PONT&f_ad1=ANDKUS CONSEIL&f_ad2=138 rue de Paris&f_ad3=&f_ad4=94220&f_ad5=CHARENTON LE PONT">ANDKUS CONSEIL</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=15&a_id=18&a_name=ANSELL&u_id=LL&tm_1=fadila.ouafi@ansell.com&tm_2=&a_ad1=Ansell - Le Cérianthe 1 - 21-23 rue du Petit Albi - BP 78395&a_ad2=95805&a_ad3=CERGY-PONTOISE CEDEX&f_ad1=ANSELL&f_ad2=Ansell - Le Cérianthe 1&f_ad3=21-23 rue du Petit Albi - BP 78395&f_ad4=95805&f_ad5=CERGY-PONTOISE CEDEX">ANSELL</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=16&a_id=19&a_name=AON FRANCE&u_id=LL&tm_1=aondrh@serviceformation.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=AON FRANCE&f_ad2=31-35 Rue de la Fédération&f_ad3=&f_ad4=75015&f_ad5=PARIS">AON FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=17&a_id=20&a_name=APPRENDRE LES LANGUES&u_id=-&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">APPRENDRE LES LANGUES</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=105&a_id=21&a_name=AREP&u_id=QB&tm_1=alexandre.bouvresse@arep.fr&tm_2=&a_ad1=16 Avenue d'IVRY
&a_ad2=75013&a_ad3=PARIS&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">AREP</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=22&a_name=AS CONNECT&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS CONNECT&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS CONNECT</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=23&a_name=AS DELIVERY&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS DELIVERY&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS DELIVERY</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=24&a_name=AS DEVOPS&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS DEVOPS&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS DEVOPS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=25&a_name=AS INFRA&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS INFRA&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS INFRA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=26&a_name=AS INTERNATIONAL&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS INTERNATIONAL&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS INTERNATIONAL</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=27&a_name=AS INTERNATIONAL GROUP&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS INTERNATIONAL GROUP&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS INTERNATIONAL GROUP</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=28&a_name=AS PRODUCTION&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS PRODUCTION&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS PRODUCTION</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=29&a_name=AS SYNERGIE&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS SYNERGIE&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS SYNERGIE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=30&a_name=AS TECHNOLOGIE&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS TECHNOLOGIE&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS TECHNOLOGIE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=19&a_id=31&a_name=AS TELECOMS ET RESEAUX&u_id=LL&tm_1=rdelageot@asinter-group.com&tm_2=mdias@asinter-group.com
&a_ad1=120, rue Réaumur&a_ad2=75002&a_ad3=PARIS&f_ad1=AS TELECOMS ET RESEAUX&f_ad2=120 - 122 rue Réaumur&f_ad3=&f_ad4=75002&f_ad5=PARIS">AS TELECOMS ET RESEAUX</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=20&a_id=32&a_name=ASSOCIATION MUSEE NATIONAL DE L'AUTOMOBILE&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=ASSOCIATION MUSEE NATIONAL AUTOMOBILE&f_ad2=192, Avenue de Colmar&f_ad3=&f_ad4=68200&f_ad5=MULHOUSE">ASSOCIATION MUSEE NATIONAL DE L'AUTOMOBILE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=21&a_id=33&a_name=ASSYSTEM FRANCE&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=ASSYSTEM FRANCE&f_ad2=23 pl de wicklow&f_ad3=&f_ad4=78180&f_ad5=MONTIGNY LE BRETONNEUX">ASSYSTEM FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=22&a_id=34&a_name=ASTRA ZENECA DUNKERQUE PRODUCTION&u_id=QB&tm_1=sylvia.clep@astrazeneca.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=ASTRA ZENECA DUNKERQUE PRODUCTION&f_ad2=224 Avenue de la Dordogne&f_ad3=&f_ad4=59640&f_ad5=DUNKERQUE">ASTRA ZENECA DUNKERQUE PRODUCTION</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=23&a_id=35&a_name=AUCHAN&u_id=QB&tm_1=cdevulder@auchan.fr&tm_2=&a_ad1=40 av. de Flandre - BP 139&a_ad2=59964&a_ad3=CROIX CEDEX&f_ad1=AUCHAN RETAIL INTERNATIONAL&f_ad2=40 Avenue de Flandre&f_ad3=BP 139&f_ad4=59964&f_ad5=CROIX CEDEX">AUCHAN</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=24&a_id=36&a_name=AUDAVIA&u_id=VG&tm_1=dchouraqui@audavia.fr&tm_2=&a_ad1=28 Avenue Montaigne&a_ad2=75008&a_ad3=PARIS&f_ad1=AUDAVIA&f_ad2=28 Avenue Montaigne&f_ad3=&f_ad4=75008&f_ad5=PARIS">AUDAVIA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=25&a_id=37&a_name=AUDENCIA&u_id=LL&tm_1=mrusch@audencia.com&tm_2=&a_ad1=  8 Route de la Jonelière&a_ad2=44312&a_ad3=NANTES CEDEX 3&f_ad1=AUDENCIA &f_ad2=8 route de la joneliere&f_ad3=BP 31222&f_ad4=44312&f_ad5=NANTES">AUDENCIA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=26&a_id=38&a_name=AVERY DENNISON FRANCE LE BOURG DE THIZY&u_id=LL&tm_1=lucie.guilloux@eu.averydennison.com&tm_2=&a_ad1=7 rue Pierre Poizat BOURG-DE-THIZY&a_ad2=69240&a_ad3=THIZY-LES-BOURGS&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">AVERY DENNISON FRANCE LE BOURG DE THIZY</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=27&a_id=39&a_name=AVIS BUDGET GROUP NETHERLANDS&u_id=QB&tm_1=ariane.abraham@avis.be&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=AVIS BUDGET GROUP NETHERLANDS&f_ad2=AVIS AUTOVERHUUR B.V&f_ad3=Louis Armstrongweg 4&f_ad4=1311 RK Almere, NL&f_ad5=">AVIS BUDGET GROUP NETHERLANDS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=27&a_id=40&a_name=AVIS LOCATION DE VOITURES SA&u_id=QB&tm_1=asli.bisan@avis-location.fr&tm_2=&a_ad1=Immeuble Linéa, 1 rue du Général Leclerc&a_ad2=92800&a_ad3=PUTEAUX&f_ad1=AVIS LOCATION DE VOITURES SA&f_ad2=Immeuble Linéa - Service Facturation&f_ad3=1 rue du Général Leclerc&f_ad4=92800&f_ad5=PUTEAUX">AVIS LOCATION DE VOITURES SA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=80&a_id=41&a_name=AVOGADRO LS&u_id=LL&tm_1=j.tryoen@amatsigroup.com&tm_2=&a_ad1=AVOGADRO LS – Parc de Génibrat&a_ad2=31470&a_ad3=FONTENILLES&f_ad1=AVOGADRO LS&f_ad2=Parc de Génibrat&f_ad3=&f_ad4=31470&f_ad5=FONTENILLES">AVOGADRO LS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=106&a_id=42&a_name=AXIANS MANAGED SERVICES PARIS - INTERACT SYSTEMES IDF S.A.S&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=AXIANS MANAGED SERVICES PARIS - INTERACT SYSTEMES IDF S.A.S&f_ad2=Parc Eiffel La Défense&f_ad3=27 rue des hautes pâtures&f_ad4=92000&f_ad5=NANTERRE">AXIANS MANAGED SERVICES PARIS - INTERACT SYSTEMES IDF S.A.S</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=28&a_id=43&a_name=AXON CABLE SAS&u_id=LL&tm_1=e.mallet@axon-cable.fr&tm_2=al.ecart@axon-cable.com&a_ad1=Route de Chalons en Champagne&a_ad2=51210&a_ad3=MONTMIRAIL&f_ad1=AXON CABLE SAS&f_ad2=45 rue Château Neuf&f_ad3=GRAND HUB - ZI MONTCOUPOT&f_ad4=51210&f_ad5=MONTMIRAIL">AXON CABLE SAS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=29&a_id=44&a_name=AXYS CONSULTANTS&u_id=VG&tm_1=francois.ballot@axys-consultants.fr&tm_2=&a_ad1= 141, rue Jules Guesde&a_ad2=92300&a_ad3=LEVALLOIS-PERRET&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">AXYS CONSULTANTS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=221&a_id=45&a_name=B O PHARM&u_id=LL&tm_1=l.ros@tridem-pharma.com&tm_2=&a_ad1=500 rue de l’Hers&a_ad2=31750&a_ad3=ESCALQUENS&f_ad1=B&O PHARM&f_ad2=500 rue de l’Hers&f_ad3=&f_ad4=31750&f_ad5=ESCALQUENS">B O PHARM</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=30&a_id=46&a_name=B2C FRANCE&u_id=LL&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">B2C FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=31&a_id=47&a_name=BASF FRANCE&u_id=LL&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">BASF FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=32&a_id=48&a_name=BAUER COMPRESSEURS&u_id=LL&tm_1=cvigot@bauer-compresseurs.com&tm_2=&a_ad1=60 av Président Franklin Roosevelt&a_ad2=73100&a_ad3=AIX LES BAINS&f_ad1=BAUER COMPRESSEURS&f_ad2=60, avenue Franklin Roosevelt&f_ad3=&f_ad4=73100&f_ad5=AIX LES BAINS">BAUER COMPRESSEURS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=33&a_id=49&a_name=BAYARD&u_id=VG&tm_1=anne-laure.piriou@bayard-presse.com&tm_2=&a_ad1=18 rue Barbès&a_ad2=92128&a_ad3=MONTROUGE&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">BAYARD</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=109&a_id=50&a_name=BIZZBEE SAS&u_id=LL&tm_1=dperrin@happychicgroup.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=BIZZBEE SAS&f_ad2=152 avenue Alfred Motte&f_ad3=&f_ad4=59100&f_ad5=ROUBAIX">BIZZBEE SAS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=34&a_id=51&a_name=BNP&u_id=VG&tm_1=natalia.kolesnikova@bnpparibas.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=BNP PARIBAS SA&f_ad2=RISK FUNCTION&f_ad3=BNPP_GRM - TSA10001&f_ad4=14913&f_ad5=CAEN CEDEX 9">BNP</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=36&a_id=52&a_name=BONDUELLE DEVELOPMENT&u_id=LL&tm_1=nharnois@bonduelle.com&tm_2=&a_ad1=161 Rue Nicolas Appert&a_ad2=59650&a_ad3=VILLENEUVE-D'ASCQ&f_ad1=BONDUELLE DEVELOPMENT&f_ad2=CS 83818&f_ad3=BP30173&f_ad4=59653&f_ad5=VILLENEUVE D'ASCQ CEDEX">BONDUELLE DEVELOPMENT</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=35&a_id=53&a_name=BONDUELLE EUROPE LONG LIFE ESTREES MONS&u_id=LL&tm_1=coralie.pietrzak@bonduelle.com&tm_2=&a_ad1=Usine d'Estrées Mons - BP 70129&a_ad2=80203&a_ad3=PERONNE CEDEX&f_ad1=BONDUELLE LONG LIFE ESTREES MONS&f_ad2=Usine d'Estrées Mons &f_ad3=BP 70129&f_ad4=80203&f_ad5=PERONNE CEDEX">BONDUELLE EUROPE LONG LIFE ESTREES MONS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=37&a_id=54&a_name=BONDUELLE EUROPE LONG LIFE RENESCURE&u_id=LL&tm_1=julie.knecht@bonduelle.com&tm_2=&a_ad1=La Woestyne&a_ad2=59173&a_ad3=RENESCURE&f_ad1=BONDUELLE LONG LIFE RENESCURE&f_ad2=RUE DE LA WOESTYNEE&f_ad3=&f_ad4=59173&f_ad5=RENESCURE">BONDUELLE EUROPE LONG LIFE RENESCURE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=36&a_id=55&a_name=BONDUELLE EUROPE LONG LIFE VILLENEUVE D'ASCQ&u_id=LL&tm_1=nharnois@bonduelle.com&tm_2=&a_ad1=161 Rue Nicolas Appert&a_ad2=59650&a_ad3=VILLENEUVE-D'ASCQ&f_ad1=BONDUELLE EUROPE LONG LIFE VILLENEUVE D'ASCQ&f_ad2=Rue Nicolas Appert - BP30173&f_ad3=SERVICE RESSOURCES HUMAINES&f_ad4=59653&f_ad5=VILLENEUVE D'ASCQ CEDEX">BONDUELLE EUROPE LONG LIFE VILLENEUVE D'ASCQ</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=36&a_id=56&a_name=BONDUELLE SA&u_id=LL&tm_1=nharnois@bonduelle.com&tm_2=&a_ad1=161 Rue Nicolas Appert&a_ad2=59650&a_ad3=VILLENEUVE-D'ASCQ&f_ad1=BONDUELLE SA&f_ad2=&f_ad3=&f_ad4=&f_ad5=">BONDUELLE SA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=36&a_id=57&a_name=BONDUELLE SAS&u_id=LL&tm_1=nharnois@bonduelle.com&tm_2=&a_ad1=161 Rue Nicolas Appert&a_ad2=59650&a_ad3=VILLENEUVE-D'ASCQ&f_ad1=BONDUELLE SAS&f_ad2=Rue Nicolas Appert&f_ad3=BP30173&f_ad4=59653&f_ad5=VILLENEUVE D'ASCQ CEDEX">BONDUELLE SAS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=109&a_id=58&a_name=BRICE SAS&u_id=LL&tm_1=dperrin@happychicgroup.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">BRICE SAS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=38&a_id=59&a_name=CARDOTECH&u_id=LL&tm_1=secretariat@cardotech.com&tm_2=&a_ad1=Vallerat&a_ad2=71390&a_ad3=SAINTE-HÉLÈNE&f_ad1=CARDOTECH&f_ad2=Vallerat&f_ad3=&f_ad4=71390&f_ad5=SAINT-HELENE">CARDOTECH</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=101&a_id=60&a_name=CASINO BARRIERE DE BIARRITZ&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CASINO BARRIERE DE BIARRITZ</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=39&a_id=61&a_name=CATELLA&u_id=LL&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CATELLA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=40&a_id=62&a_name=CEGEDIM&u_id=LL&tm_1=mery.badji@cegedim.com&tm_2=&a_ad1=137 rue d'Aguesseau&a_ad2=92100&a_ad3=BOULOGNE-BILLANCOURT&f_ad1=CEGEDIM&f_ad2=84 Boulevard Vivier-Merle&f_ad3=&f_ad4=69003&f_ad5=LYON">CEGEDIM</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=40&a_id=63&a_name=CEGEDIM IT&u_id=LL&tm_1=mery.badji@cegedim.com&tm_2=&a_ad1=137 rue d'Aguesseau&a_ad2=92100&a_ad3=BOULOGNE-BILLANCOURT&f_ad1=CEGEDIM IT&f_ad2=137 rue d'Aguesseau&f_ad3=&f_ad4=92100&f_ad5=BOULOGNE BILLANCOURT">CEGEDIM IT</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=40&a_id=64&a_name=CEGEDIM LOGICIELS MEDICAUX FRANCE&u_id=LL&tm_1=marieisabelle.moinet@smart-rx.com&tm_2=&a_ad1=137 rue d'Aguesseau&a_ad2=92100&a_ad3=BOULOGNE-BILLANCOURT&f_ad1=CEGEDIM LOGICIELS MEDICAUX FRANCE&f_ad2=110 rue d'Aguesseau&f_ad3=&f_ad4=92100&f_ad5=BOULOGNE BILLANCOURT">CEGEDIM LOGICIELS MEDICAUX FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=40&a_id=65&a_name=CEGEDIM SOFTWARE&u_id=LL&tm_1=mery.badji@cegedim.com&tm_2=&a_ad1=137 rue d'Aguesseau&a_ad2=92100&a_ad3=BOULOGNE-BILLANCOURT&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CEGEDIM SOFTWARE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=40&a_id=66&a_name=CEGEDIM SRH&u_id=LL&tm_1=mery.badji@cegedim.com&tm_2=&a_ad1=137 rue d'Aguesseau&a_ad2=92100&a_ad3=BOULOGNE-BILLANCOURT&f_ad1=CEGEDIM SRH&f_ad2=137 rue d'Aguesseau&f_ad3=&f_ad4=92100&f_ad5=BOULOGNE BILLANCOURT">CEGEDIM SRH</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=41&a_id=67&a_name=CELL AND CO&u_id=QB&tm_1=lguinot@cell-and-co.com&tm_2=&a_ad1=Rue de Chambussière&a_ad2=63430&a_ad3=PONT-DU-CHÂTEAU&f_ad1=CELL & CO&f_ad2=ZAC de Champ Lamet&f_ad3=Rue de Chambussière&f_ad4=63430&f_ad5=PONT DU CHÂTEAU">CELL AND CO</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=42&a_id=68&a_name=CELLECTIS&u_id=LL&tm_1=delphine.jay@cellectis.com&tm_2=juliette.nicole@cellectis.com&a_ad1=8 rue de la Croix Jarry 75013 Paris&a_ad2=&a_ad3=&f_ad1=CELLECTIS SA&f_ad2=8 rue de la Croix Jarry&f_ad3=&f_ad4=75013&f_ad5=PARIS">CELLECTIS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=43&a_id=69&a_name=CENTRALE NANTES&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=CENTRALE NANTES&f_ad2=&f_ad3=1 rue de la noe&f_ad4=44300&f_ad5=NANTES">CENTRALE NANTES</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=44&a_id=70&a_name=CENTRE VACANCES BERRY TUDY&u_id=LL&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CENTRE VACANCES BERRY TUDY</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=40&a_id=71&a_name=CETIP&u_id=-&tm_1=christelle.nigay@cegedim-activ.com&tm_2=&a_ad1=114 rue d'Aguesseau&a_ad2=92100&a_ad3=BOULOGNE BILLANCOURT&f_ad1=CETIP&f_ad2=114 rue d'Aguesseau&f_ad3=&f_ad4=92100&f_ad5=BOULOGNE BILLANCOURT">CETIP</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=46&a_id=72&a_name=CEVA SANTE ANIMALE&u_id=LL&tm_1=aude.caudroit@ceva.com&tm_2=&a_ad1=10 av. de la Ballastière&a_ad2=33500&a_ad3=LIBOURNE&f_ad1=CEVA SANTE ANIMALE&f_ad2=10 av. de la Ballastière 
&f_ad3=&f_ad4=33500&f_ad5=LIBOURNE FRANCE">CEVA SANTE ANIMALE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=47&a_id=73&a_name=CHAMPAGNE BILLECART SALMON&u_id=QB&tm_1=mallaury@champagne-billecart.fr&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=CHAMPAGNE BILLECART SALMON&f_ad2=40, rue Carnot&f_ad3=&f_ad4=51160&f_ad5=MAREUIL SUR AY">CHAMPAGNE BILLECART SALMON</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=48&a_id=74&a_name=CHAMPAGNE DANIEL ADAM FILS &u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=SAS CHAMPAGNE DANIEL ADAM & FILS&f_ad2=19 Rue de Chigny&f_ad3=&f_ad4=51500&f_ad5=RILLY-LA-MONTAGNE">CHAMPAGNE DANIEL ADAM FILS </a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=49&a_id=75&a_name=CHATEAU D'EAU&u_id=QB&tm_1=badria.taibi@chateaudeau.com&tm_2=&a_ad1=CHATEAU D'EAU - 141 rue rateau&a_ad2=93120&a_ad3=LA COURNEUVE&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CHATEAU D'EAU</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=50&a_id=76&a_name=CHELA +&u_id=QB&tm_1=dounia.beksas@chela.fr&tm_2=&a_ad1=30 Rue de la Varenne&a_ad2=94100&a_ad3=SAINT-MAUR-DES-FOSSÉS&f_ad1=CHELA +&f_ad2= 30 Rue de la Varenne&f_ad3=&f_ad4=94100&f_ad5=SAINT MAUR DES FOSSES">CHELA +</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=52&a_id=77&a_name=CLARIANT PLASTICS AND COATINGS&u_id=LL&tm_1=nathalie.saligari@clariant.com&tm_2=&a_ad1=1995 route de la vallée du Giffre&a_ad2=74490&a_ad3=SAINT JEOIRE EN FAUCIGNY&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CLARIANT PLASTICS AND COATINGS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=52&a_id=78&a_name=CLARIANT PRODUCTION FRANCE&u_id=LL&tm_1=nathalie.saligari@clariant.com&tm_2=&a_ad1=QUAI SUD&a_ad2=76470&a_ad3=LE TREPORT&f_ad1=CLARIANT PRODUCTION (FRANCE)&f_ad2=QUAI SUD&f_ad3=&f_ad4=76470&f_ad5=LE TREPORT">CLARIANT PRODUCTION FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=52&a_id=79&a_name=CLARIANT SE SUCCURSALE FRANCE&u_id=LL&tm_1=estelle.ribault@clariant.com&tm_2=&a_ad1=CLARIANT - ZAC de la Grange&a_ad2=41200&a_ad3=ROMORANTIN LANTHENAY&f_ad1=CLARIANT SE SUCCURSALE France&f_ad2=6, rue Louise Michel&f_ad3=&f_ad4=94600&f_ad5=CHOISY LE ROI">CLARIANT SE SUCCURSALE FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=53&a_id=80&a_name=CLEANIS&u_id=QB&tm_1=anne.thomas@innothera.com&tm_2=&a_ad1=CLEANIS, 22 avenue Aristide Briand&a_ad2=94110&a_ad3=ARCUEIL&f_ad1=CLEANIS&f_ad2=22 avenue Aristide Briand &f_ad3=&f_ad4=94110&f_ad5=ARCUEIL">CLEANIS</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=54&a_id=81&a_name=COFARCO&u_id=LL&tm_1=cesar.daniel@cofarco.com&tm_2=&a_ad1=Cofarco SAS - 88, rue Lafayette&a_ad2=75009&a_ad3=PARIS&f_ad1=COFARCO SAS&f_ad2=88 rue La Fayette&f_ad3=&f_ad4=75009&f_ad5=PARIS">COFARCO</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=24&a_id=82&a_name=COLOPLAST&u_id=VG&tm_1=dchouraqui@audavia.fr&tm_2=&a_ad1=28 Avenue Montaigne&a_ad2=75008&a_ad3=PARIS&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">COLOPLAST</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=15&a_id=83&a_name=COMASEC&u_id=LL&tm_1=martine.gaigne@ansell.com&tm_2=&a_ad1=21-23 rue du Petit Albi - BP 78395&a_ad2=95805&a_ad3=CERGY-PONTOISE CEDEX&f_ad1=COMASEC&f_ad2=21-23 rue du Petit Albi&f_ad3=BP 78395&f_ad4=95805&f_ad5=CERGY-PONTOISE CEDEX">COMASEC</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=55&a_id=84&a_name=CONSEIL DEPARTEMENTAL DE L'ESSONNE&u_id=QB&tm_1=&tm_2=&a_ad1=Boulevard de France&a_ad2=91012&a_ad3=ÉVRY&f_ad1=Conseil départemental de l'Essonne&f_ad2=Hôtel du département
&f_ad3=Boulevard de France&f_ad4=91012&f_ad5=EVRY CEDEX">CONSEIL DEPARTEMENTAL DE L'ESSONNE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=56&a_id=85&a_name=CPF FRANCE&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CPF FRANCE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=57&a_id=86&a_name=CPF FRANCE MKT&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CPF FRANCE MKT</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=58&a_id=87&a_name=CRISTAL CO&u_id=LL&tm_1=alexandra.gusto@cristalco.com&tm_2=&a_ad1=27 rue Châteaubriand&a_ad2=75008&a_ad3=PARIS&f_ad1=CRISTAL CO&f_ad2=Comptabilité fournisseurs&f_ad3=CS14&f_ad4=45490&f_ad5=CORBEILLES EN GATINAIS">CRISTAL CO</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=59&a_id=88&a_name=CRISTAL-UNION&u_id=LL&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CRISTAL-UNION</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=60&a_id=89&a_name=CRYSTAL GROUP&u_id=LL&tm_1=amandine.loiselet@crystalgroup.fr&tm_2=ketura.telon@crystalgroup.fr&a_ad1=Rue du Meunier&a_ad2=95700&a_ad3=ROISSY-EN-FRANCE&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">CRYSTAL GROUP</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=61&a_id=90&a_name=DARAMIC&u_id=QB&tm_1=amgarrigue@daramic.com&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=DARAMIC SAS&f_ad2=25 Rue Westrich&f_ad3=&f_ad4=67600&f_ad5=SÉLESTAT">DARAMIC</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=62&a_id=91&a_name=DB CONSEIL&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=DB CONSEIL&f_ad2=843 Chemin des taillades &f_ad3=&f_ad4=84830&f_ad5=SERIGNAN-DU-COMTAT">DB CONSEIL</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=63&a_id=92&a_name=DELOITTE ET ASSOCIES&u_id=QB&tm_1=mchabalier@deloitte.fr&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=DELOITTE ET ASSOCIES&f_ad2=TSA 20303&f_ad3=&f_ad4=92030&f_ad5=LA DEFENSE CEDEX">DELOITTE ET ASSOCIES</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=64&a_id=93&a_name=DGAC&u_id=VG&tm_1=christine.francois@aviation-civile.gouv.fr&tm_2=&a_ad1=50 rue Henry-Farman&a_ad2=75720&a_ad3=PARIS&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">DGAC</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=65&a_id=94&a_name=DIACCURATE&u_id=LL&tm_1=&tm_2=&a_ad1=5 RUE DE LA BAUME&a_ad2=75008&a_ad3=PARIS&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">DIACCURATE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=66&a_id=95&a_name=DIPA&u_id=VG&tm_1=o.buffet@cemoi.fr&tm_2=&a_ad1=2980 AVENUE JULIEN PANCHOT&a_ad2=66000&a_ad3=PERPIGNAN&f_ad1=&f_ad2=&f_ad3=&f_ad4=&f_ad5=">DIPA</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=169&a_id=96&a_name=DIRAMODE&u_id=LL&tm_1=florence.fontaine@pimkie.com&tm_2=&a_ad1=1 rue John Hadley&a_ad2=59654&a_ad3=VILLENEUVE D'ASCQ&f_ad1=DIRAMODE&f_ad2=1 rue John Hadley&f_ad3=&f_ad4=59654&f_ad5=VILLENEUVE D'ASCQ">DIRAMODE</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=67&a_id=97&a_name=DXC TECHNOLOGY&u_id=QB&tm_1=&tm_2=&a_ad1=&a_ad2=&a_ad3=&f_ad1=DXC TECHNOLOGY&f_ad2=Tour carpe diem cs4007 &f_ad3=31 pl des corolles &f_ad4=92400&f_ad5=COURBEVOIE">DXC TECHNOLOGY</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=68&a_id=98&a_name=EBV ELEKTRONIK&u_id=LL&tm_1=jocelyne.thinon@ebv.com&tm_2=&a_ad1=2-6 Place du Général de Gaulle&a_ad2=92184&a_ad3=ANTONY&f_ad1=EBV ELEKTRONIK&f_ad2=2-6 Place du Général de Gaulle&f_ad3=CS 70046&f_ad4=92184&f_ad5=ANTONY CEDEX">EBV ELEKTRONIK</a><br>
<a href="http://winegroup.synten.com/manager/lms3/parser/import_account.cfm?g_id=69&a_id=99&a_name=EDF DIVISION COMBUSTIBLE NUCLEAIRE&u_id=LL&tm_1=vincent.combes@edf.fr&tm_2=&a_ad1=1 PLACE PLEYEL DIVISION COMBUSTIBLE NUCLEAIRE&a_ad2=93200&a_ad3=SAINT DENIS&f_ad1=EDF DIVISION COMBUSTIBLE NUCLEAIRE&f_ad2=DIVISION COMBUSTIBLE NUCLEAIRE&f_ad3=1 PLACE PLEYEL&f_ad4=93200&f_ad5=SAINT DENIS">EDF DIVISION COMBUSTIBLE NUCLEAIRE</a><br>